<a href="https://colab.research.google.com/github/brittabeta/Learning-Sandbox/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy is a package for scientific computing built around the ndarray object, an N dimensional array object.  NumPy has highly optimized computational tools.

The ndarray object size is set at creation and cannot be resized, it contains a single data type, and are not limited to two dimensions.

The ndarray can be reshaped, returning a new array object...

In [1]:
import numpy as np

# Create NumPy Arrays

sequence argument

argument is a list

In [7]:
data = [1,2,3,4]
first_array = np.array(data)
first_array

array([1, 2, 3, 4])

constructor

argument is a list of lists

In [8]:
data = [[1,2,3],
	[4,5,6],
	[7,8,9]]
my_array = np.array(data)

In [9]:
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ones Method

In [10]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Zeros Method

In [11]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Arange Method

arguments

start

stop

step

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# Dimensions and NumPy

In [19]:
oned = np.arange(21)

Shape, Dimension, Size

In [20]:
oned.shape

(21,)

In [21]:
oned.ndim

1

In [22]:
oned.size

21

Two Dimensions

list of lists

In [23]:
list_o_lists = [[1,2,3],[4,5,6],[7,8,9]]
twod = np.array(list_o_lists)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
twod.ndim

2

In [25]:
twod.size

9

In [26]:
twod.shape

(3, 3)

Reshape

dimensions are arguments

In [28]:
oned = np.arange(12)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
twod = oned.reshape(3,4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
twod.shape

(3, 4)

Higher Dimensions

In [34]:
threed = twod.reshape(2,2,3)
threed

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
threed.shape

(2, 2, 3)

In [36]:
threed.ndim

3

# Setting Data Type

In [37]:
darray = np.arange(100)
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
darray.dtype

dtype('int64')

In [39]:
darray.nbytes

800

choose a dtype

In [40]:
darray = np.arange(100, dtype=np.int8)

In [41]:
darray.dtype

dtype('int8')

In [42]:
darray.nbytes

100

### Caution: a misleading output

In [44]:
darray[12] = 0.4
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int8)

In [45]:
darray[12]

0

you cannot combine float and int, or int8 and int64

output 0 is 0.4 with .4 stripped off

# Broadcasting and Dimensions

In [46]:
A1 = np.array([[1,2,3],
		[4,5,6],
		[7,8,9]])
A1.shape

(3, 3)

In [47]:
A2 = np.array([[1,1,1],
		[1,1,1],
		[1,1,1]])
A2.shape

(3, 3)

add the arrays

In [48]:
A1 + A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

add a single value

In [50]:
A3 = A1 + 3
A3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
A3.shape

(3, 3)

shape of the result matches the array

add arrays of different shape

In [52]:
A3 = np.array([1,1,1])
A3.shape

(3,)

In [53]:
A1 + A3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Broadcasting, the result of operations between arrays is expanded out to an array that has the maximum dimensions for the respective dimension

In [54]:
A4 = np.arange(10).reshape(2,1,5)
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [55]:
A4.shape

(2, 1, 5)

In [56]:
A5 = np.arange(14).reshape(2,7,1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [57]:
A5.shape

(2, 7, 1)

In [59]:
A6 = A4 + A5
A6

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18],
        [15, 16, 17, 18, 19],
        [16, 17, 18, 19, 20],
        [17, 18, 19, 20, 21],
        [18, 19, 20, 21, 22]]])

In [60]:
A6.shape

(2, 7, 5)

# Matrix Operations

In [2]:
M1 = np.arange(9).reshape(3,3)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
M2 = np.arange(2,11).reshape(3,3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Matrix Transpose

In [4]:
M1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Diagonal

In [5]:
M1.diagonal()

array([0, 4, 8])

Matrix Product

In [6]:
M1@M2

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

Matrix_multiplication_qtl1.svg

Matrix_multiplication_diagram_2.svg

Mmult_factory_svg.svg